name: 📦 Publish package on release

#on:
#  release:
#    types: [published]
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: echo "👉 npm install"
      - run: echo "👉 npm build"
      - run: echo "Publishing package version ${{ github.event.release.tag_name }}""
      - run: echo "👉 npm publish --access public"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}          